name: Build Java + Docker

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build clinica-veterinaria-api
        working-directory: ./clinica-veterinaria-api
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ghcr.io/clinica-veterinaria-api:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/clinica-veterinaria-api:${{ github.sha }}
        
      - name: Build service-email
        working-directory: ./servico-email
        run: mvn clean package -DskipTests
        
      - name: Build Docker image
        run: docker build -t ghcr.io/servico-email:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/servico-email:${{ github.sha }}
        
